export type Category = {
    name: string;
    iconKey: string;
    color: string;
    value: string;
    description: string;
    subcategories: string[];
};

export const CATEGORIES: Category[] = [
    {
        name: "Véhicules",
        iconKey: "vehicules",
        color: "#E53935",
        value: "vehicules",
        description: "Voitures, motos, pièces détachées et tout pour vos déplacements.",
        subcategories: [
            "Voitures",
            "Motos & Scooters",
            "Camions & Bus",
            "Véhicules utilitaires",
            "Location de véhicules",
            "Pièces détachées auto",
            "Pièces détachées moto",
            "Accessoires auto",
            "Engins & Tracteurs",
            "Bateaux & Nautisme",
            "Tricycles & Remorques",
        ],
    },
    {
        name: "Immobilier",
        iconKey: "immobilier",
        color: "#1E88E5",
        value: "immobilier",
        description: "Appartements, maisons, terrains et locaux à vendre ou louer.",
        subcategories: [
            "Villas",
            "Appartements",
            "Appartements meublés",
            "Studios",
            "Chambres & Colocation",
            "Terrains",
            "Terrains agricoles",
            "Immeubles",
            "Bureaux & Commerces",
            "Entrepôts & Magasins",
            "Maisons de vacances",
            "Fermes & Vergers",
        ],
    },
    {
        name: "Électronique",
        iconKey: "electronique",
        color: "#43A047",
        value: "electronique",
        description: "Smartphones, ordinateurs, accessoires et gadgets high-tech.",
        subcategories: [
            "Téléphones portables",
            "Tablettes",
            "Ordinateurs portables",
            "Ordinateurs de bureau",
            "Accessoires téléphonie",
            "Accessoires informatiques",
            "Télévisions",
            "Box & Décodeurs",
            "Vidéoprojecteurs",
            "Casques & Écouteurs",
            "Haut-parleurs & Enceintes",
            "Appareils photo & Caméras",
            "Montres connectées",
            "GPS & Trackers",
            "Jeux vidéo & Consoles",
            "Imprimantes & Scanners",
            "Composants & Pièces",
            "Autres électronique",
        ],
    },
    {
        name: "Électroménager",
        iconKey: "electromenager",
        color: "#5C6BC0",
        value: "electromenager",
        description: "Réfrigérateurs, climatiseurs, machines à laver et petit électroménager.",
        subcategories: [
            "Réfrigérateurs & Congélateurs",
            "Cuisinières & Gazinières",
            "Fours & Micro-ondes",
            "Climatiseurs",
            "Ventilateurs",
            "Machines à laver",
            "Sèche-linge",
            "Fers à repasser & Défroisseurs",
            "Mixeurs, Blenders & Robots",
            "Bouilloires & Cafetières",
            "Aspirateurs",
            "Autres électroménager",
        ],
    },
    {
        name: "Mode & Beauté",
        iconKey: "mode",
        color: "#FFB300",
        value: "mode",
        description: "Vêtements, chaussures, bijoux et produits de beauté.",
        subcategories: [
            "Vêtements Femme",
            "Vêtements Homme",
            "Chaussures Femme",
            "Chaussures Homme",
            "Montres",
            "Bijoux & Fantaisie",
            "Sacs & Maroquinerie",
            "Valises & Bagagerie",
            "Parfums Femme",
            "Parfums Homme",
            "Cosmétiques & Soins",
            "Perruques & Extensions",
            "Tissus & Pagnes",
            "Foulards & Voiles",
            "Lingerie",
            "Lunettes de soleil",
            "Ceintures & Cravates",
        ],
    },
    {
        name: "Pour l'enfant",
        iconKey: "enfant",
        color: "#EC407A",
        value: "enfant",
        description: "Vêtements, jouets et équipement pour bébés et enfants.",
        subcategories: [
            "Vêtements bébé (0-2 ans)",
            "Vêtements enfant (3-12 ans)",
            "Vêtements ado (13-16 ans)",
            "Chaussures enfant",
            "Poussettes & Porte-bébés",
            "Lits & Berceaux",
            "Chaises hautes & Sièges auto",
            "Jouets & Jeux éducatifs",
            "Fournitures scolaires",
            "Couches & Soins bébé",
            "Alimentation bébé",
        ],
    },
    {
        name: "Pour la maison",
        iconKey: "maison",
        color: "#8E24AA",
        value: "maison",
        description: "Meubles, décoration, literie et tout pour votre intérieur.",
        subcategories: [
            "Canapés & Fauteuils",
            "Tables & Chaises",
            "Lits & Sommiers",
            "Armoires & Rangements",
            "Meubles de cuisine",
            "Meubles de bureau",
            "Décoration intérieure",
            "Luminaires",
            "Rideaux & Voilages",
            "Tapis & Moquettes",
            "Literie & Matelas",
            "Vaisselle & Ustensiles",
            "Jardin & Plein air",
            "Piscines & Accessoires",
            "Bricolage & Outillage",
        ],
    },
    {
        name: "Sports & Loisirs",
        iconKey: "loisirs",
        color: "#9C27B0",
        value: "loisirs",
        description: "Sport, fitness, musique, livres et divertissements.",
        subcategories: [
            "Football",
            "Basketball & Handball",
            "Fitness & Musculation",
            "Natation & Plage",
            "Arts martiaux & Boxe",
            "Vélos & Trottinettes",
            "Instruments de musique",
            "Livres & Magazines",
            "DVDs & Blu-ray",
            "Art & Collections",
            "Événements & Billetterie",
            "Voyages & Tourisme",
            "Camping & Randonnée",
            "Jeux de société",
        ],
    },
    {
        name: "Emplois",
        iconKey: "emploi",
        color: "#1E88E5",
        value: "emplois",
        description: "Offres et demandes d'emploi, stages et formations.",
        subcategories: [
            "Offres d'emploi",
            "Demandes d'emploi",
            "Stages & Apprentissage",
            "Travail temporaire & Intérim",
            "Freelance & Missions",
            "Formations & Certifications",
        ],
    },
    {
        name: "Services",
        iconKey: "services",
        color: "#00ACC1",
        value: "services",
        description: "Cours, ménage, réparations et services professionnels.",
        subcategories: [
            "Cours particuliers & Soutien scolaire",
            "Babysitting & Nounou",
            "Ménage & Repassage",
            "Cuisine & Traiteur",
            "Plomberie & Électricité",
            "Maçonnerie & Carrelage",
            "Peinture & Décoration",
            "Jardinage & Espaces verts",
            "Déménagement & Transport",
            "Livraison & Courses",
            "Covoiturage",
            "Design graphique & Web",
            "Photographie & Vidéo",
            "Couture & Retouche",
            "Coiffure & Beauté à domicile",
            "Réparation électronique",
            "Mécanique auto",
            "Conseils juridiques & Comptabilité",
            "Événementiel & Animation",
        ],
    },
    {
        name: "Animaux",
        iconKey: "animaux",
        color: "#00897B",
        value: "animaux",
        description: "Animaux de compagnie, accessoires et services vétérinaires.",
        subcategories: [
            "Chiens",
            "Chats",
            "Oiseaux",
            "Poissons & Aquariophilie",
            "Moutons & Chèvres",
            "Poules & Volailles",
            "Lapins",
            "Chevaux & Ânes",
            "Alimentation animale",
            "Accessoires & Cages",
            "Toilettage & Soins",
            "Services vétérinaires",
        ],
    },
    {
        name: "Alimentation",
        iconKey: "alimentation",
        color: "#43A047",
        value: "alimentation",
        description: "Produits alimentaires, boissons, épices et vente en gros.",
        subcategories: [
            "Fruits & Légumes",
            "Viandes & Poissons",
            "Céréales & Farines",
            "Épices & Condiments",
            "Produits laitiers",
            "Boissons",
            "Pâtisserie & Boulangerie",
            "Produits locaux",
            "Vente en gros",
            "Traiteur & Plats cuisinés",
        ],
    },
    {
        name: "Matériel Pro",
        iconKey: "pro",
        color: "#546E7A",
        value: "pro",
        description: "Équipements, outillage et matériaux pour professionnels.",
        subcategories: [
            "Matériel agricole",
            "Matériel BTP & Construction",
            "Matériaux de construction",
            "Groupes électrogènes",
            "Panneaux solaires & Énergie",
            "Matériel de soudure",
            "Outillage professionnel",
            "Fournitures de bureau",
            "Matériel de restauration",
            "Matériel de commerce",
            "Matériel médical",
            "Matériel de coiffure & beauté",
            "Caméras & Surveillance",
            "Transport & Manutention",
            "Imprimerie & Sérigraphie",
        ],
    },
];
