export type Category = {
    name: string;
    iconKey: string;
    color: string;
    value: string;
    description: string;
    subcategories: string[];
};

export const CATEGORIES: Category[] = [
    {
        name: "Véhicules",
        iconKey: "vehicules",
        color: "#E53935",
        value: "vehicules",
        description: "Voitures, motos, pièces détachées et tout pour vos déplacements au quotidien.",
        subcategories: [
            "Voitures",
            "Motos & Scooters",
            "Camions & Bus",
            "Location de véhicules",
            "Accessoires & Pièces détachées",
            "Bateaux",
        ],
    },
    {
        name: "Immobilier",
        iconKey: "immobilier",
        color: "#1E88E5",
        value: "immobilier",
        description: "Appartements, maisons, terrains et locaux commerciaux à vendre ou louer.",
        subcategories: [
            "Villas",
            "Appartements",
            "Appartements meublés",
            "Terrains",
            "Immeubles",
            "Bureaux & Commerces",
            "Chambres & Colocation",
            "Maisons de vacances",
            "Terrains agricoles",
            "Fermes & Vergers",
        ],
    },
    {
        name: "Électronique",
        iconKey: "electronique",
        color: "#43A047",
        value: "electronique",
        description: "Smartphones, tablettes, accessoires et gadgets high-tech pour tous.",
        subcategories: [
            "Téléphones & Tablettes",
            "Ordinateurs & Laptops",
            "Accessoires Téléphonie",
            "Accessoires Informatiques",
            "TV, Box & Vidéoprojecteurs",
            "Son, Hifi & Casques",
            "Appareils photos & Caméras",
            "Montres connectées & GPS",
            "Jeux vidéo & Consoles",
            "Imprimantes & Photocopieurs",
            "Autres électronique",
        ],
    },
    {
        name: "Électroménager",
        iconKey: "electromenager",
        color: "#5C6BC0",
        value: "electromenager",
        description: "Réfrigérateurs, climatiseurs, machines à laver et petit électroménager.",
        subcategories: [
            "Réfrigérateurs & Congélateurs",
            "Cuisinières, Gazinières & Fours",
            "Climatiseurs & Ventilateurs",
            "Machines à laver",
            "Petit électroménager",
            "Autres électroménager",
        ],
    },
    {
        name: "Mode & Beauté",
        iconKey: "mode",
        color: "#FFB300",
        value: "mode",
        description: "Vêtements, chaussures, bijoux et produits de beauté pour hommes et femmes.",
        subcategories: [
            "Vêtements Femme",
            "Vêtements Homme",
            "Chaussures Femme",
            "Chaussures Homme",
            "Montres & Bijoux",
            "Maroquinerie & Bagagerie",
            "Cosmétique & Parfums",
            "Accessoires cheveux, Coiffure & Cils",
            "Tissus & Foulards",
            "Lingerie",
            "Lunettes",
            "Autres accessoires",
        ],
    },
    {
        name: "Pour l'enfant",
        iconKey: "enfant",
        color: "#EC407A",
        value: "enfant",
        description: "Vêtements, chaussures, jouets et équipement pour bébés et enfants.",
        subcategories: [
            "Vêtements Enfants",
            "Chaussures Enfants",
            "Mobilier & Équipement bébé",
            "Jeux & Jouets",
            "Fournitures Scolaires",
            "Autres",
        ],
    },
    {
        name: "Pour la maison",
        iconKey: "maison",
        color: "#E53935",
        value: "maison",
        description: "Meubles, décoration, literie et tout pour embellir votre intérieur.",
        subcategories: [
            "Meubles",
            "Décoration & Luminaires",
            "Literie & Matelas",
            "Linges de maison",
            "Vaisselle",
            "Jardin & Piscine",
            "Bricolage",
            "Autres pour la maison",
        ],
    },
    {
        name: "Sports & Loisirs",
        iconKey: "loisirs",
        color: "#9C27B0",
        value: "loisirs",
        description: "Sport, fitness, instruments de musique et divertissements pour tous.",
        subcategories: [
            "Sport & Fitness",
            "Vélos & Trottinettes",
            "Instruments de musique",
            "DVDs, CDs & Livres",
            "Art & Artisanat",
            "Événements & Billetterie",
            "Voyage & Tourisme",
            "Autres Sports & Loisirs",
        ],
    },
    {
        name: "Emplois",
        iconKey: "emploi",
        color: "#1E88E5",
        value: "emplois",
        description: "Offres d'emploi, demandes d'emploi et formations professionnelles.",
        subcategories: [
            "Offres d'emploi",
            "Demandes d'emploi (CVs)",
            "Formations & Certifications",
        ],
    },
    {
        name: "Services",
        iconKey: "services",
        color: "#00ACC1",
        value: "services",
        description: "Cours particuliers, ménage, livraisons et services professionnels divers.",
        subcategories: [
            "Cours particuliers",
            "Babysitting & Nounou",
            "Ménage & Cuisine",
            "Travaux, Bricolage & Jardinage",
            "Courses, Livraisons & Déménagement",
            "Covoiturage",
            "Services Web, Design & Photo",
            "Services Mode, Beauté & Bien-être",
            "Autres services",
        ],
    },
    {
        name: "Animaux",
        iconKey: "animaux",
        color: "#00897B",
        value: "animaux",
        description: "Animaux de compagnie, accessoires et tout pour le bien-être de vos compagnons.",
        subcategories: [
            "Chiens",
            "Chats",
            "Moutons",
            "Poules, Lapins & Pigeons",
            "Matériel pour animaux",
            "Autres animaux",
        ],
    },
    {
        name: "Alimentation",
        iconKey: "alimentation",
        color: "#43A047",
        value: "alimentation",
        description: "Produits alimentaires, boissons, épices et vente en gros.",
        subcategories: [
            "Produits alimentaires",
            "Boissons",
            "Épices & Condiments",
            "Vente en gros",
        ],
    },
    {
        name: "Matériel Pro",
        iconKey: "pro",
        color: "#546E7A",
        value: "pro",
        description: "Équipements, outillage et matériaux pour professionnels du BTP et artisans.",
        subcategories: [
            "Matériel Agricole",
            "Transport & Manutention",
            "Matériaux Construction & BTP",
            "Fournitures de Bureau",
            "Matériel Marchés & Commerces",
            "Matériel Médical",
            "Énergie, Groupes électrogènes & Panneaux solaires",
            "Caméras & Matériel de surveillance",
            "Autres matériel pro",
        ],
    },
];
